IF EXISTS (SELECT 1 FROM dbo.TA_PABELLON WHERE PABS_NOMBRE = 'UQ_NOMBRE_PABELLON')
BEGIN
	ALTER TABLE dbo.TA_PABELLON DROP CONSTRAINT UQ_NOMBRE_PABELLON;
END
    ALTER TABLE dbo.TA_PABELLON ADD CONSTRAINT UQ_NOMBRE_PABELLON UNIQUE (PABS_NOMBRE);
GO

IF EXISTS (SELECT 1 FROM dbo.TA_NICHO WHERE NICS_CODNICHO = 'UQ_NOMBRE_NICHO')
BEGIN
	ALTER TABLE dbo.TA_NICHO DROP CONSTRAINT UQ_NOMBRE_NICHO;
END
    ALTER TABLE dbo.TA_NICHO ADD CONSTRAINT UQ_NOMBRE_NICHO UNIQUE (NICS_CODNICHO);
GO

IF EXISTS (SELECT 1 FROM dbo.TA_DIFUNTO WHERE DIFS_DNI = 'UQ_DIFUNTO_DNI')
BEGIN
	ALTER TABLE dbo.TA_DIFUNTO DROP CONSTRAINT UQ_DIFUNTO_DNI;
END
    ALTER TABLE dbo.TA_DIFUNTO ADD CONSTRAINT UQ_DIFUNTO_DNI UNIQUE (DIFS_DNI);
GO
